### ISSUE TITLE
bitsandbytes compiled with no gpu support. (Install no longer works)

### ISSUE THREAD

**Issue by bbecausereasonss** [oobabooga/text-generation-webui#1164]
### Describe the bug

WSL/Ubuntu was working until I pulled latest commit. Now it's busted, tried re-installing but same errors.... Also on latest GPTQ from the main repo.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install WSL steps, launch

### Logs

```shell
(textgen) xxxx@Perplexity:~/text-generation-webui$ python server.py --model TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g --wbits 4 --groupsize 128 --model_type llama --chat --verbose --listen --share --disk --gpu-memory 18
bin /home/xxxx/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/xxxx/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
```

### System Info

```shell
WSL2/Ubuntu
```

**Comment by bbecausereasonss** [comment]
FYI, windows has also been broken since last commit.

**Comment by jllllll** [comment]
https://github.com/oobabooga/text-generation-webui/issues/1174#issuecomment-1508294477

**Comment by jllllll** [comment]
Compiled a 0.38.1 wheel, kinda scuffed, but it worked for the model I tested it on.

Open `micromamba-cmd.bat` and enter this:
```
python -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/raw/main/bitsandbytes-0.38.1-py3-none-any.whl --force-reinstall
```

**Comment by bbecausereasonss** [comment]
Thanks but no luck in WSL or Linux. Cuda library error in Linux and no name error just quitting in windows.

**Comment by jllllll** [comment]
This is specifically for Windows. What was the no name error?

**Comment by bbecausereasonss** [comment]
Just tried installing from scratch again and got this error.. Any help please? I installed this GPTQ by cloning into repo dir and then doing install -r requirements. 

https://github.com/qwopqwop200/GPTQ-for-LLaMa

>
(textgen) perplexity@Perplexity:~/text-generation-webui$ python server.py --model TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g --wbits 4 --groupsize 128 --model_type llama --chat --verbose --listen --share --disk --gpu-memory 18
bin /home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g...
Could not find the quantized model in .pt or .safetensors format, exiting...

**Comment by factoidforrest** [comment]
Broken on ubuntu as well

**Comment by bbecausereasonss** [comment]
Yeah I'm on WSL/Ubuntu and just can't get it to install/work

**Comment by bbecausereasonss** [comment]
Also on Windows either my models just do not load and do not throw an error, or produce gibberish...

Starting the web UI...
Loading MetaIX_Alpaca-30B-Int4-128G-Safetensors...
Found the following quantized model: models\MetaIX_Alpaca-30B-Int4-128G-Safetensors\alpaca-30b-128g-4bit.safetensors
Loading model ...
Press any key to continue . . .

**Comment by jllllll** [comment]
@bbecausereasonss The Windows installer installs oobabooga's fork of GPTQ which is too old for the newer models. I have a wheel compiled for the newest GPTQ if you want to upgrade on Windows.

On Linux, make sure that you cloned the cuda branch and not the main one.

**Comment by bbecausereasonss** [comment]
> @bbecausereasonss The Windows installer installs oobabooga's fork of GPTQ which is too old for the newer models. I have a wheel compiled for the newest GPTQ if you want to upgrade on Windows.
> 
> On Linux, make sure that you cloned the cuda branch and not the main one.

Can you link me to the cuda branch? Yea if you can share the wheel I'd love to try it in Win too. Thanks

**Comment by jllllll** [comment]
@bbecausereasonss

`git clone https://github.com/qwopqwop200/GPTQ-for-LLaMa -b cuda`

The Windows wheel can be installed with:
```
python -m pip install https://github.com/jllllll/GPTQ-for-LLaMa-Wheels/raw/main/610fdae6588c2b17bcf2726cacaaf795cd45077e/quant_cuda-0.0.0-cp310-cp310-win_amd64.whl --force-reinstall
```
You will still need to clone the repo, the wheel only contains the kernels.

**Comment by bbecausereasonss** [comment]
Gah, thanks just cloned that specific branch in WSL/Ubuntu and still getting same error.

(textgen) perplexity@Perplexity:~/text-generation-webui$ python server.py --model MetaIX_Alpaca-30B-Int4-128G-Safetensors --verbose --wbits 4 --groupsize 128 --model_type llama --chat --share --disk --gpu-memory 18
bin /home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading MetaIX_Alpaca-30B-Int4-128G-Safetensors...
Could not find the quantized model in .pt or .safetensors format, exiting...

**Comment by jllllll** [comment]
@bbecausereasonss Did you compile the kernels after cloning?

**Comment by bbecausereasonss** [comment]
> @bbecausereasonss Did you compile the kernels after cloning?

For WSL/Ubuntu?  No, how do I do that?

**Comment by jllllll** [comment]
> > @bbecausereasonss Did you compile the kernels after cloning?
> 
> For WSL/Ubuntu? No, how do I do that?

cd into the GPTQ-for-LLaMa folder and run this:
`python setup_cuda.py install`

You may need the c++ compiler from `sudo apt install build-essential`

**Comment by bbecausereasonss** [comment]
Hmm. Just did that but got same error :/

(textgen) perplexity@Perplexity:~/text-generation-webui$ python server.py --model TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g --wbits 4 --groupsize 128 --model_type llama --chat --verbose --listen --share --disk --gpu-memory 18
bin /home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g...
Could not find the quantized model in .pt or .safetensors format, exiting...

**Comment by jllllll** [comment]
Could be an issue with torch. Run this: `python -m torch.utils.collect_env`
See if you get `Is CUDA available: True`

**Comment by bbecausereasonss** [comment]
Yep Cuda available is true.

**Comment by bbecausereasonss** [comment]
Could it be related to nvidia drivers needing to be installed in WSL/Ubuntu? I did install the cuda toolkit.

**Comment by jllllll** [comment]
I'm sorry, I'm an idiot. Try this: `pip install bitsandbytes --force-reinstall`

If that doesn't get it working, I'll post some instructions on compiling it from source. Though, that will take a while.

**Comment by bbecausereasonss** [comment]
lol... why is this so busted. It was working great before the last few pulls.

(textgen) perplexity@Perplexity:~/text-generation-webui$ python server.py --model TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g --wbits 4 --groupsize 128 --model_type llama --chat --verbose --listen --share --disk --gpu-memory 18
Traceback (most recent call last):
  File "/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 70, in <module>
    import cchardet as chardet
ModuleNotFoundError: No module named 'cchardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perplexity/text-generation-webui/server.py", line 21, in <module>
    import gradio as gr
  File "/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/components.py", line 51, in <module>
    from gradio import media_data, processing_utils, utils
  File "/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/utils.py", line 39, in <module>
    import aiohttp
  File "/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/aiohttp/client.py", line 59, in <module>
    from .client_reqrep import (
  File "/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 72, in <module>
    import charset_normalizer as chardet  # type: ignore[no-redef]
  File "/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/charset_normalizer/__init__.py", line 23, in <module>
    from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
  File "/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/charset_normalizer/api.py", line 10, in <module>
    from charset_normalizer.md import mess_ratio
AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)

**Comment by bbecausereasonss** [comment]
Okay installed cchardet and now still same error lol

(textgen) perplexity@Perplexity:~/text-generation-webui$ python server.py --model TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g --wbits 4 --groupsize 128 --model_type llama --chat --verbose --listen --share --disk --gpu-memory 18
bin /home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g...
Found the following quantized model: models/TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g/vicuna-13B-1.1-GPTQ-4bit-128g.safetensors
Loading model ...

**Comment by jllllll** [comment]
I honestly don't know about bitsandbytes. Took me ages to get a working Windows version of it.

Try removing `--disk --gpu-memory 18` as those don't work with 4-bit models anyway. Also try removing `--model_type llama`

There used to be more info messages for solving these issues, but it's hidden now for some reason. Did you add your cuda installation to LD_LIBRARY_PATH?

**Comment by jllllll** [comment]
If you didn't add your cuda path to LD_LIBRARY_PATH, then do this:

Run this: `find / -name libcudart.so 2>/dev/null`
Then this: `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_ABOVE`
Replace FOUND_PATH_FROM_ABOVE with the path that the first command found.

**Comment by bbecausereasonss** [comment]
Good lord. Took me forever to find this. 

Only thing worked was > 

pip install -i https://test.pypi.org/simple/ bitsandbytes-cuda113

**Comment by cblomert** [comment]
> Good lord. Took me forever to find this.
> 
> Only thing worked was >
> 
> pip install -i https://test.pypi.org/simple/ bitsandbytes-cuda113

this worked for me - thanks <3

**Comment by CBevers** [comment]
> Compiled a 0.38.1 wheel, kinda scuffed, but it worked for the model I tested it on.
> 
> Open `micromamba-cmd.bat` and enter this:
> 
> ```
> python -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/raw/main/bitsandbytes-0.38.1-py3-none-any.whl --force-reinstall
> ```
> 
> Please let me know if it works for you.

Here's my result. Note I'm using Anaconda here instead of Miniconda in an attempt to troubleshoot this issue:

`Gradio HTTP request redirected to localhost :)
bin /home/user/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/user/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:152: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/user/anaconda3/envs/textgen/lib/libcudart.so'), PosixPath('/home/user/anaconda3/envs/textgen/lib/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: CUDA runtime path found: /home/user/anaconda3/envs/textgen/lib/libcudart.so
/home/user/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:152: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Required library version not found: libbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Setup Failed!
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "/home/user/text-generation-webui/server.py", line 44, in <module>
    from modules import chat, shared, training, ui
  File "/home/user/text-generation-webui/modules/training.py", line 13, in <module>
    from peft import (LoraConfig, get_peft_model, prepare_model_for_int8_training,
  File "/home/user/anaconda3/envs/textgen/lib/python3.10/site-packages/peft/__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "/home/user/anaconda3/envs/textgen/lib/python3.10/site-packages/peft/mapping.py", line 16, in <module>
    from .peft_model import (
  File "/home/user/anaconda3/envs/textgen/lib/python3.10/site-packages/peft/peft_model.py", line 31, in <module>
    from .tuners import (
  File "/home/user/anaconda3/envs/textgen/lib/python3.10/site-packages/peft/tuners/__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "/home/user/anaconda3/envs/textgen/lib/python3.10/site-packages/peft/tuners/lora.py", line 40, in <module>
    import bitsandbytes as bnb
  File "/home/user/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/user/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/user/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/user/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/user/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/user/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues`

**Comment by jllllll** [comment]
@CBevers That wheel is compiled specifically for Windows. There is no need for it on Linux as bitsandbytes already supplies a pre-compiled Linux wheel through pip. This wheel is needed for Windows as bitsandbytes only supports Linux.
