### ISSUE TITLE
Make the default "character_bias-bias string" a ghost text

### ISSUE THREAD

**Issue by Xabab** [oobabooga/text-generation-webui#117]
Some users might use this only for setting up a particular response from a character, thus use it rarely. Deleting it every time when loading the page is annoying at the least and it sometimes is forgotten to do.

**Comment by oobabooga** [comment]
It is already possible to create custom default for extension parameters using a settings.json file. For instance,

```
"google_translate-language string": "fr",
```

inside `settings.json` while calling the script with `python server.py --settings settings.json`.

I think that it's better to leave an useless but descriptive default value because it helps people understand what this extension does and how it should be used.

**Comment by Xabab** [comment]
@oobabooga I meant a placeholder, like this:
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_placeholder

With old `*I speak in annoyingly cute voice*` but in the form of placeholder it:
+ will stay just as descriptive
+ won't throw off new people, who somehow did not open the extensions tab and can not understand why their character speaks so annoyingly
+ will not brother those, who have it on but leave it empty most of the time
