### ISSUE TITLE
How to load Erebus model from Colab?

### ISSUE THREAD

**Issue by conanak99** [oobabooga/text-generation-webui#130]
Currently, the Colab only show Pygmalion model.

1. How can we load another model from collab?
2. Will the chat work if we use other models (Erebus for example)?

**Comment by oobabooga** [comment]
I would like to add the Erebus models to Colab as well. The problem is that Colab is a peculiar system with more GPU memory than RAM, and the HuggingFace model loader first loads each entire shard into memory (the pytorch_*.bin files) before sending it to the GPU. This causes the session to crash when trying to load 12GB shards like Erebus has.

A workaround for Pygmalion has been to reshard the models into smaller chunks and reupload them.

I have created an issue on transformers about this:

https://github.com/huggingface/transformers/issues/21376

**Comment by conanak99** [comment]
Thanks for answering. I tried to update the code in Colab and try to load the model, but it failed due to RAM issue too 😞 .
