### ISSUE TITLE
The model auto loading? A button or confirmation?

### ISSUE THREAD

**Issue by Ph0rk0z** [oobabooga/text-generation-webui#1345]
I find myself getting in trouble with the model auto load in the UI. On some occasions it will inadvertently scroll up and start loading another model. If this is a 30b it is of course going to take a while to finish loading the model I *don't* want.

On other occasions I have both 4-bit and FP16 models in the same folder. Because "4-bit" isn't in the folder name, the FP16 will load and again I will be waiting until it finishes or have to break the whole server.py script.

I propose that maybe we do not load the model until a button is pressed after selection. That way the correct group size/bits or other desired parameters can be set.

**Comment by bloodsign** [comment]
Yeah, I think it's better to have a button to apply the change in model/option. Couple of times, I expand the dropdown and select a model, only to forget that I haven't set the wbits and groupsize yet for 4-bit models, I had to reload the model re set the proper options or because the model loaded improperly and got an error.
