### ISSUE TITLE
This app can't run on your PC 

### ISSUE THREAD

**Issue by uckthis** [oobabooga/text-generation-webui#167]
This appears 4-5 times before install closes.
![Untitled](https://user-images.githubusercontent.com/28671050/222977537-ac448a05-003d-4fae-b82e-a3da46a76e0e.png)

OS: Windows 10x64 Enterprise

**Comment by Ph0rk0z** [comment]
Run as admin? It says access is denied.

**Comment by uckthis** [comment]
@Ph0rk0z Yes. Also with GPU and CPU and tried all drives as well.

**Comment by Ph0rk0z** [comment]
Manually run the commands in the batch and set up microconda that way.

**Comment by uckthis** [comment]
@Ph0rk0z It exits even when I -h. It's not installed, so no commands to run.

**Comment by Ph0rk0z** [comment]
In an elevated command prompt? Also that is some rando micromamba from github. Try to use conda or a different one and make sure it's not the wrong architecture. That's where I've seen an error like this before.

**Comment by oobabooga** [comment]
Maybe the CPU architecture is arm64 @uckthis? I suppose the current micromamba installer only works on amd64.

**Comment by uckthis** [comment]
Trying Conda now.

**Comment by uckthis** [comment]
Conda installed in elevated. Thank you, all.

**Comment by VictorZakharov** [comment]
I installed conda, but same issue. I tried elevated cmd prompt also, no dice.

**Comment by LoganDark** [comment]
if you are getting this error about certificate revocation:

![image](https://user-images.githubusercontent.com/4723091/227839014-4286fdce-37d7-48fe-b9b8-9343615b964c.png)

(I get this because my firewall blocks CRLs)

Add `--insecure` flag to the curl command inside install.bat

ex.

there is a line that starts with `curl -L`

make it `curl --insecure -L`

YOU DO NOT NEED ADMIN ACCESS TO INSTALL THIS
