### ISSUE TITLE
Inpropoer support on Open Assistant

### ISSUE THREAD

**Issue by MilesQLi** [oobabooga/text-generation-webui#1721]
**Description**

Open Assistant uses <|prompter|>, <|endoftext|>, and <|assistant|> as the special tokens. They are not included in the code. 

**Additional Context**

Please see https://huggingface.co/OpenAssistant/stablelm-7b-sft-v7-epoch-3 for an example.

**Comment by LaaZa** [comment]
Isn't this it? https://github.com/oobabooga/text-generation-webui/blob/main/characters/instruction-following/Open%20Assistant.yaml

**Comment by CarlKenner** [comment]
This is caused by the fact that every other version of Open Assistant contains `oasst` in the filename, but that one doesn't. We can probably fix it by also checking for "openassistant" (the model downloader includes the organisation name before the model name) but that won't work if someone else mirrors it, and it will give false positives for models hosted by OpenAssistant that aren't actually the OpenAssistant model. Or we can check for that specific name and make an exception for it.

In the meantime, the workaround is to scroll down in the Chat window and manually choose Instruct then choose the Open Assistant character.

Don't expect good results though, as that model is based on StableLM and StableLM is garbage.

**Comment by MilesQLi** [comment]
> This **bug** (not enhancement) is caused by the fact that every other version of Open Assistant contains `oasst` in the filename, but that one doesn't. We can probably fix it by also checking for "openassistant" (the model downloader includes the organisation name before the model name) but that won't work if someone else mirrors it, and it will give false positives for models hosted by OpenAssistant that aren't actually the OpenAssistant model. Or we can check for that specific name and make an exception for it.
> 
> In the meantime, the workaround is to scroll down in the Chat window and manually choose Instruct then choose the Open Assistant character.
> 
> Don't expect good results though, as that model is based on StableLM and StableLM is garbage.
> 
> EDIT: Actually, the bug is caused by us only recognising a single specific filename as oasst. It's more broken than I thought. Anyway, I'm fixing it now.

Got it. Thanks a lot for the information!
