### ISSUE TITLE
error loading model: missing tok_embeddings.weight with custom quantized Cerebras

### ISSUE THREAD

**Issue by micsthepick** [oobabooga/text-generation-webui#1751]
### Describe the bug

I quantised a Cerebras 13B using GGML, and I can infer with the gpt-2 executable, but not with the web ui.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Download Cerebras 13B, and latest GGML,
convert Cerebras 13B to f16 ggml as follows (from same conda env):
`python examples/gpt-2/convert-cerebras-to-ggml.py ../models/Cerebras-GPT-13B`
then quantise:
`./bin/gpt-2-quantize ../models/Cerebras-GPT-13B/ggml-model-f16.bin ../models/Cerebras-13B-ggml-q5_1/Cerebras-13B.ggml.q5_1.bin 9`

### Logs

```shell
Loading Cerebras-GPT-13B-GGML-5_1...
llama.cpp weights detected: ../Models/Cerebras-GPT-13B-GGML-5_1/Cerebras-13B.ggml.q5_1.bin

llama.cpp: loading model from ../Models/Cerebras-GPT-13B-GGML-5_1/Cerebras-13B.ggml.q5_1.bin
error loading model: missing tok_embeddings.weight
llama_init_from_file: failed to load model
```

### System Info

```shell
MacBook Air M1, 2020, 16GB, Ventura 13.3.1 (a)
latest text-generation-webui and dependencies from master
```

**Comment by mironkraft** [comment]
It seems you are having issues loading the quantized Cerebras 13B model with the web UI after using GGML for quantization. The error message `missing tok_embeddings.weight` indicates that there is an issue with the model weights.

You can try this from my poin of view:

1. Verify the conversion process: Double-check the conversion and quantization commands you used to ensure they were executed correctly. Make sure there were no error messages or warnings during the conversion and quantization process.

2. Model file structure: Inspect the generated model file structure and verify that all necessary files are present, including `tok_embeddings.weight`. If any files are missing, it may be necessary to re-run the conversion and quantization process.

3. Test with the GPT-2 executable: Since you mentioned that the model works with the GPT-2 executable, try comparing the file structure and configuration between the working setup and the web UI setup. There might be differences in how the model is loaded or processed, which could lead to the issue.

4. Update libraries and dependencies: Ensure that all required libraries and dependencies (e.g., Gradio, PyTorch, etc.) are up-to-date and compatible with the quantized model.

5. Reach out to the GGML project: If none of the above steps resolve the issue, you might consider reaching out to the GGML project maintainers or authors for further assistance, as they might have more insights into potential issues with the conversion and quantization process.

Keep in mind that as both text-generation-webui and GGML are open-source projects, it is possible that some specific combinations of models and settings might not work out-of-the-box and may require manual adjustments or fixes.

Hope helped...
