### ISSUE TITLE
Make Repo SFW?

### ISSUE THREAD

**Issue by HanSeoulOh** [oobabooga/text-generation-webui#178]
Requesting @oobabooga to make the codebase SFW like the sister repo https://github.com/AUTOMATIC1111/stable-diffusion-webui

**Comment by oobabooga** [comment]
What is NSFW about the repository?

**Comment by Titaniumtown** [comment]
What is the issue with the codebase @HanSeoulOh 
I didn't know there was anything NSFW included. Are you referring to the checks done after stable diffusion produces an image to make sure it is SFW?

**Comment by HanSeoulOh** [comment]
There's no direct nsfw but the repo usage examples use models known to generate NSFW content (and is labeled explicitly as such by the owner themselves) e.g. https://colab.research.google.com/github/oobabooga/AI-Notebooks/blob/main/Colab-TextGen-GPU.ipynb 

Maybe sanitize the repo a bit more to make it more safe for work such as making the presets folder a bit more like the models and softprompt folder?

**Comment by Titaniumtown** [comment]
Why?

**Comment by oobabooga** [comment]
While it is true that the Pygmalion model used in the sample Colab notebook has been trained trained on a partially NSFW dataset, I find that it only generates NSFW outputs if you deliberately prompt it in this direction. Otherwise, it remains neutral.

All models can generate NSFW content with minimal prompt engineering, including GPT-J and OPT.

The `presets` folder only contains text files with parameters that can be used by any model.

I'd be against including explicitly vulgar material in the repository, but it doesn't look like that's an issue right now.
