### ISSUE TITLE
Can't manually run 'download-model.py' anymore

### ISSUE THREAD

**Issue by silvestron** [oobabooga/text-generation-webui#1857]
### Describe the bug

`download-model.py` is broken when I try to run it manually. Only tried on native Windows 11.

Downloading models from the web UI works fine.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Either double-click on or run `download-model.py` through a terminal.

### Logs

```shell
Traceback (most recent call last):
  File "C:\oobabooga_windows\text-generation-webui\download-model.py", line 18, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

### System Info

```shell
Windows 11
One click installer
RTX 3060 12GB
```

**Comment by Nostrovx** [comment]
Hi, same problem.
I tried starting fresh with the new 1 click install and it tells me 'requests' is missing although on my old version still works.

**Comment by silvestron** [comment]
I guess I can reinstall, but I wonder what broke my current installation.

**Comment by Nostrovx** [comment]
My problems started after the latest update.

**Comment by silvestron** [comment]
I did a clean install but that didn't solve the problem.

**Comment by hungryformelons** [comment]
I have the same issue and i installed it using the latest one-click-installer start_windows.bat

**Comment by sleeplessinva** [comment]
Just did a fresh install because when I ran the "update" it broke the manual download. So I nuked the environment entirely and did new install and the same error message I got before the update is here, though it's different than the error that other people above me in the thread have indicated. This is on a windows environment and can be reproduced.

Traceback (most recent call last):
  File "D:\env\1_oobabooga_windows\text-generation-webui\download-model.py", line 223, in <module>
    model, branch = downloader.sanitize_model_and_branch_names(model, branch)
  File "D:\env\1_oobabooga_windows\text-generation-webui\download-model.py", line 31, in sanitize_model_and_branch_names
    if model[-1] == '/':
TypeError: 'NoneType' object is not subscriptable

**Comment by RamennBowls** [comment]
Hi @sleeplessinva,
Looking at comit 5dfe0be (from two days ago), they've actually removed the entire model selection menu. The error you ran into is likely because you haven't specified the model you want to download, within the command itself (e.g. `python download-model.py facebook/opt-1.3b`).

At the moment, it appears there's no proper error handling for if a user forgets to specify the model name, as it would usually just load the menu instead. Basically just an oversight.

Hope this helps! (｡•̀ᴗ-)✧👍

**Comment by silvestron** [comment]
I installed requests globally

```
pip install requests
```

and that solved the problem.
