### ISSUE TITLE
"Instruct Joi (Contrastive Search)" preset is missing a do_sample = False

### ISSUE THREAD

**Issue by SillyLossy** [oobabooga/text-generation-webui#197]
Hello!

The included "Instruct Joi Contrastive Search" preset doesn't actually activate the contrastive search generation mode, as it requires the `do_sample` parameter to be `false`, but it's unset/true in the preset, hence the preset really uses the sampling generation mode.

Please refer to this code from the Transformers library: 
https://github.com/huggingface/transformers/blob/main/src/transformers/generation/utils.py#L1323

On a side note: We also found that the real contrastive search (when you uncheck do_sample) consumes a lot of VRAM that grows exponentially with the top_k parameter: 5 is the max for inferring on 24 GB, given the 6B parameter model is loaded in 16-bit mode, any higher values will throw an OOM.

**Comment by oobabooga** [comment]
You are absolutely right, thanks for informing me. I had found that preset [here](https://huggingface.co/Rallio67/joi_20B_instruct_alpha) originally and assumed it corresponded to Contrastive Search because there was a `penalty_alpha=0.6` among the parameters.

I have deleted that preset and added a new CS one with `top_k=4`   following the example somewhere in your link:

```
        >>> outputs = model.contrastive_search(
        ...     **input_ids, penalty_alpha=0.6, top_k=4, stopping_criteria=stopping_criteria
        ... )

```

**Comment by Darksoulmaster31** [comment]
I found some problems with this change.
A line in the code `module/shared.py` was not changed in the new commit, so it still defaults to
`Instruct Joi (Contrastive Search)` instead of the new `Contrastive Search` _(line 45)_.

Also, setting `do_sample` to **false** causes the GPT-Neo-X Instruct fine-tuned models (such as Joi) to fail, since they don't even support Contrastive Search, resulting in the following error:
`ValueError: GPTNeoXForCausalLM does not support caching and therefore **can't** be used for contrastive search.`

However it works for other models though, such as Llama. (I tried the 4-bit 7B model with the preset)
