### ISSUE TITLE
Separate dev branch from master

### ISSUE THREAD

**Issue by Xabab** [oobabooga/text-generation-webui#2141]
Cloning main as is, often lead to fatal exceptions, as with new features, new bugs emerge here and there. For users that want to use cutting edge version of this repo, currently there are such options: 
- with any luck find a stable commit and hold onto it for several seances 
- fix bugs themselves

I propose to separate stable-ish builds (?) into a 'stable' branch and cutting edge, straight-from-the-commit builds into a 'nightly' branch.

**Comment by tr7zw** [comment]
Please, or someone make a stable fork of the repo. Used it the last time on the 6th, and now wanted to use it again. I pulled the changes, suddenly it refuses to load the model because it tries to put it into system memory, auto-devices not working, the update script spitting all kinds of errors, webui not even starting. 
This makes it a horrible experience for anyone not breathing and living Python, especially compared to repos like https://github.com/vladmandic/automatic .
