### ISSUE TITLE
many vicuna models and poor documentation on those that are compatible with text-generative-webui.

### ISSUE THREAD

**Issue by valdesguefa** [oobabooga/text-generation-webui#2222]
many users experience errors such as :
Llama' object has no attribute 'ctx
or 'LlamaCppModel' object has no attribute 'model' because the model versions we use are obsolete, yet they have been used in many tutorials or documentation. It would help a lot to know which model versions to use and where to find them.

**Comment by slashbored** [comment]
Good idea, getting started with LLMs and it can be a bit confusing at times.

For anyone coming here, looking for a solution.

This is due to the change of the quantisation methods in llama.cpp which hasn't been included in llama-cpp-python, as far as I can tell even not in the 0.1.52 version, see https://github.com/abetlen/llama-cpp-python/pull/251. Tried some messing around myself, but can't get it myself to work again. If youre looking at TheBlokes models on HF, on the specific model -> Files and versions and select "previous_llama_ggmlv2". There, you can download the "old" ggml versions and place them in the models folder under the corresponding folder for that model. These work for me right now.

**Comment by SoshyHayami** [comment]
Getting the same error, updated to 0.1.52 and Downloaded Manticore 13b ggmlv3. but nope, doesn't work.
the only GGML model that works is the q5.1 version of gpt4-x-vicuna 13b.

**Comment by oobabooga** [comment]
That's an upstream issue with llama.cpp
