### ISSUE TITLE
KeyError: 'llama' when I run python3.9 server.py

### ISSUE THREAD

**Issue by ShadowStorm0** [oobabooga/text-generation-webui#223]
When I run `python3.9 server.py` with the folder llama-7b in the models directory, I get this error KeyError: 'llama'.

Full Log: https://paste.sethforprivacy.com/?79d37085983ff6dc=#BMSLkWFnKKesn9rVK4faUwGKNh4rK2NmssBQvXTLxxUT

Anyone how why this is happening?

**Comment by oobabooga** [comment]
Try this

```
pip uninstall transformers
pip install git+https://github.com/zphang/transformers@llama_push

```

**Comment by ShadowStorm0** [comment]
I am following these instructions but for the convert_llama_weights_to_hf.py script I can not locate the config.json that it needed
*Inside ~/LLaMA-HF/llama-7b folder*
![Screenshot from 2023-03-10 14-41-30](https://user-images.githubusercontent.com/41564329/224424388-098cccc0-fa21-4402-9041-9aa960bc4535.png)

**Comment by ShadowStorm0** [comment]
oh the config file you see in the picture was after I renamed it, sorry for any confusion

**Comment by ShadowStorm0** [comment]
I get a different error after I try doing that `KeyError: 'n_layers'`

**Comment by ShadowStorm0** [comment]
I mean to write, it could not locate the 'params.json' file

**Comment by ShadowStorm0** [comment]
I get a `FileNotFoundError: [Errno 2] No such file or directory:` for `~/7B/params.json`

**Comment by ShadowStorm0** [comment]
I got it working. So apparently I had to specify pip3.9

**Comment by nameless0704** [comment]
> Try this
> 
> ```
> pip uninstall transformers
> pip install git+https://github.com/zphang/transformers@llama_push
> ```

Does this repository no longer exist?

**Comment by judyhappy** [comment]
> When I run `python3.9 server.py` with the folder llama-7b in the models directory, I get this error KeyError: 'llama'.
> 
> Full Log: https://paste.sethforprivacy.com/?79d37085983ff6dc=#BMSLkWFnKKesn9rVK4faUwGKNh4rK2NmssBQvXTLxxUT
> 
> Anyone how why this is happening?

I am also meeting such issue. Could you please share the way to fix this error:

```
Traceback (most recent call last):
  File "run_clm.py", line 548, in <module>
    main()
  File "run_clm.py", line 315, in main
    config = AutoConfig.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/configuration_auto.py", line 917, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/configuration_auto.py", line 623, in __getitem__
    raise KeyError(key)
KeyError: 'llama'
```

**Comment by PavlovIgor** [comment]
I have encountered the same problem and I cannot understand what the reason is. Two days ago there were no problems.

`Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fastchat/model/apply_delta.py", line 49, in <module>
    apply_delta(args.base_model_path, args.target_model_path, args.delta_path)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fastchat/model/apply_delta.py", line 14, in apply_delta
    base = AutoModelForCausalLM.from_pretrained(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 917, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 623, in __getitem__
    raise KeyError(key)
KeyError: 'llama'`

**Comment by edsonke** [comment]
To anyone experiencing a similar issue, you may find this command helpful:
`pip install -U transformers`

**Comment by Crabbit-F** [comment]
I got a wired question when I build 'llasm_Chinese_llama2_7B' model which is 'KeyError: 'llaaa''. And it doesn't work after I tried 'pip install -U transformers', 'pip install git+https://github.com/huggingface/transformers' or 'pip install git+https://github.com/zphang/transformers@llama_push'. And I tried transformer vision 4.31, 4.34, 4.35. Has anyone encountered the same problem?
![llama](https://github.com/oobabooga/text-generation-webui/assets/52477243/ffdbe5d1-ef01-4629-9857-b1bab7bc3c4e)
