### ISSUE TITLE
Can't update 30/05/2023 (10:12 AM GMT)

### ISSUE THREAD

**Issue by Simplegram** [oobabooga/text-generation-webui#2432]
### Describe the bug

Today I can't update oobabooga text generation webui using `update_windows.bat`. Logs of the error have been included. Is this supposed to happen? 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Update with `update_windows.bat` file within the next few hours(?)

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/34500695/a854d17a-55ce-4e2f-bdfa-19b5766f57f1)

### Logs

```shell
error: Your local changes to the following files would be overwritten by merge:
        modules/AutoGPTQ_loader.py
Please commit your changes or stash them before you merge.
Aborting
Updating 60ae80c..0db4e19
Command '"E:\Projects\cpy\llms\textgen-webui-gpu\installer_files\conda\condabin\conda.bat" activate "E:\Projects\cpy\llms\textgen-webui-gpu\installer_files\env" >nul && git pull' failed with exit status code '1'. Exiting...

Done!
Press any key to continue . . .
```

### System Info

```shell
Windows 11
MSI RTX 4090 Suprim X
Local Install
```

**Comment by Simplegram** [comment]
Nevermind. After a few google search, I found out this was caused by Github's overwrite protection. I have changed a few lines from `AutoGPTQ_loader.py`.

Executing this in the command prompt fixed the issue. If you want to keep the changes, back the file up before doing this.
```
git checkout HEAD^ modules/AutoGPTQ_loader.py
```

**Comment by HotChocut** [comment]
I also had this happen to me with the same hardware but on Windows 10, in case others run into this issue I found that it was caused whenever I change some files locally and then try to update. To fix it I just deleted these locally changed files (in @Simplegram's case above it would be "modules/AutoGPTQ_loader.py" as stated on line 2 in the logs), then remade my local changes after updating.
In case you are thinking to just rename the file in question and delete the newly generated one after updating so you can use your old one again, I would not recommend that. This is because the file in question was one that needed to be updated so if you delete the new one and use the old one the code will be different and you can cause errors. This is why I make the changes again afterwards on the new file instead of the old one, so that I can avoid that.
Hope this helps someone!
