### ISSUE TITLE
OpenAI API extension with ExLlama does not return a proper response.

### ISSUE THREAD

**Issue by trigger-happy** [oobabooga/text-generation-webui#2731]
### Describe the bug

When attempting to use the OpenAI API extension together with a model loaded with ExLlama, the response is always `You are a helpful assistant. Answer as concisely as possible.`

I did a bit of digging and found that it always returns the [context message](https://github.com/oobabooga/text-generation-webui/blob/d8d29edf54f224ba3b0daa36fce8fcae8125aa64/extensions/openai/script.py#L281).

When loaded with AutoGPTQ, the API works as expected.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
curl http://localhost:5001/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
     "model": "TheBloke_airoboros-33B-gpt4-1.2-GPTQ",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7
   }'
```
Change the port according to what the OpenAI API server is listening on. The response will always be some variation of the following.
```
{"id": "chatcmpl-1686975981", "object": "chat.completions", "created": 1686975981, "model": "TheBloke_airoboros-33B-gpt4-1.2-GPTQ", "choices": [{"index": 0, "finish_reason": "stop", "message": {"role": "assistant", "content": "You are a helpful assistant. Answer as concisely as possible."}}], "usage": {"prompt_tokens": 27, "completion_tokens": 14, "total_tokens": 41}}
```

### Logs

```shell
I'm getting the following from the server

2023-06-17 04:17:20 INFO:Loading TheBloke_airoboros-33B-gpt4-1.2-GPTQ...
2023-06-17 04:17:22 INFO:Loaded the model in 2.11 seconds.

10.244.17.87 - - [17/Jun/2023 04:20:19] "POST /v1/chat/completions HTTP/1.1" 200 -
10.244.17.87 - - [17/Jun/2023 04:20:26] "POST /v1/chat/completions HTTP/1.1" 200 -
10.244.17.87 - - [17/Jun/2023 04:26:12] "POST /v1/chat/completions HTTP/1.1" 200 -
10.244.17.87 - - [17/Jun/2023 04:26:15] "POST /v1/chat/completions HTTP/1.1" 200 -
10.244.17.87 - - [17/Jun/2023 04:26:21] "POST /v1/chat/completions HTTP/1.1" 200 -
```
```


### System Info

```shell
Using my custom docker image built from https://github.com/trigger-happy/docker-images/tree/master/text-generation-webui.

GPU model is Nvidia RTX 4090 on an Ubuntu 22.04 host system. Containerd as the container runtime with nvidia-container-runtime configured and enabled.
```

**Comment by matatonic** [comment]
Yes, I found this also, it doesn't honor the echo=False parameter yet. streaming works as expected, so as a workaround until it's fixed you can enable stream=True.

**Comment by matatonic** [comment]
@oobabooga I'm not sure how to fix this, I've dug into the code and it looks like exllama isn't getting the echo=False or honoring is_chat=False and is returning the prompt back from: generate_reply(..., is_chat=False) .. Stranger still, only the prompt is being returned and not the generated text - and I can hear the GPU generating text, it's just lost somewhere.
This only happens when stream=False, stream=True works fine. AutoGPT and other custom generators (Ex. llama.cpp) work fine.

It seems like it needs a text = text[len(prompt):] somewhere and under some is_chat/echo conditions, but I'm sure where to put it because only exllama seems to have this issue and I don't want to break llama.cpp.

**Comment by trigger-happy** [comment]
It's pretty hacky, but [this](https://github.com/oobabooga/text-generation-webui/compare/main...trigger-happy:text-generation-webui:main) is what I've come up with so far to workaround the issue without using `stream=True`.

**Comment by matatonic** [comment]
I just realized the fact that only the prompt is returned is probably expected, we add an extra stopping string of the user name, but it's the first thing that comes after the context so will stop the generated text immediately after the context. So, the problem is just that the prompt is echoed back, nothing more.

**Comment by matatonic** [comment]
> It's pretty hacky, but [this](https://github.com/oobabooga/text-generation-webui/compare/main...trigger-happy:text-generation-webui:main) is what I've come up with so far to workaround the issue without using `stream=True`.

I think I like the "fix" from the other thread better, it fixes both problems (but also probably breaks llama.cpp in some cases)

**Comment by atisharma** [comment]
Just to confirm I'm also getting just my system prompt echoed back.

**Comment by oobabooga** [comment]
I think that this fixes this issue https://github.com/oobabooga/text-generation-webui/commit/cbd63eeeff246a13f9a943ba7067bd1bd2b1012e

**Comment by matatonic** [comment]
That did it, working great! Thanks.

**Comment by HvskyAI** [comment]
Confirming that the issue no longer occurs with the latest commit. Thanks for taking a look.

**Comment by trigger-happy** [comment]
I can confirm that the issue is fixed. Many thanks @oobabooga !
