### ISSUE TITLE
unload_model() not working with exllama 

### ISSUE THREAD

**Issue by matatonic** [oobabooga/text-generation-webui#2743]
### Describe the bug

unload_model() doesn't free GPU memory when a model is loaded with exllama.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load a model with exllama, click unload model in the webui, no change in GPU memory. Loading another model will add to memory usage (and probably OOM).

### Logs

```shell
llm-text-generation-webui-1  | 2023-06-18 07:39:26 INFO:Loading TheBloke_Wizard-Vicuna-13B-Uncensored-GPTQ...
llm-text-generation-webui-1  | ----------------------------------------
llm-text-generation-webui-1  | Exception occurred during processing of request from ('192.168.128.1', 43038)
llm-text-generation-webui-1  | Traceback (most recent call last):
llm-text-generation-webui-1  |   File "/usr/lib/python3.10/socketserver.py", line 683, in process_request_thread
llm-text-generation-webui-1  |     self.finish_request(request, client_address)
llm-text-generation-webui-1  |   File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
llm-text-generation-webui-1  |     self.RequestHandlerClass(request, client_address, self)
llm-text-generation-webui-1  |   File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
llm-text-generation-webui-1  |     self.handle()
llm-text-generation-webui-1  |   File "/usr/lib/python3.10/http/server.py", line 432, in handle
llm-text-generation-webui-1  |     self.handle_one_request()
llm-text-generation-webui-1  |   File "/usr/lib/python3.10/http/server.py", line 420, in handle_one_request
llm-text-generation-webui-1  |     method()
llm-text-generation-webui-1  |   File "/app/extensions/api/blocking_api.py", line 256, in do_POST
llm-text-generation-webui-1  |     raise e
llm-text-generation-webui-1  |   File "/app/extensions/api/blocking_api.py", line 248, in do_POST
llm-text-generation-webui-1  |     shared.model, shared.tokenizer = load_model(shared.model_name)
llm-text-generation-webui-1  |   File "/app/modules/models.py", line 65, in load_model
llm-text-generation-webui-1  |     output = load_func_map[loader](model_name)
llm-text-generation-webui-1  |   File "/app/modules/models.py", line 277, in ExLlama_loader
llm-text-generation-webui-1  |     model, tokenizer = ExllamaModel.from_pretrained(model_name)
llm-text-generation-webui-1  |   File "/app/modules/exllama.py", line 41, in from_pretrained
llm-text-generation-webui-1  |     model = ExLlama(config)
llm-text-generation-webui-1  |   File "/app/repositories/exllama/model.py", line 630, in __init__
llm-text-generation-webui-1  |     tensor = tensor.to(device, non_blocking = True)
llm-text-generation-webui-1  | torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 34.00 MiB (GPU 0; 23.63 GiB total capacity; 21.81 GiB already allocated; 69.56 MiB free; 21.84 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### System Info

```shell
Ubuntu 22, docker nvidia/cuda:11.8.0-devel-ubuntu22.04, Nvidia 4090, Driver Version: 525.105.17   CUDA Version: 12.0
```

**Comment by Ph0rk0z** [comment]
Indeed, there appears to be no way to unload the model in the repo.

**Comment by abrisene** [comment]
I'm also getting cuda OOM errors on subsequent model loads with ExLllama on WSL.

Restarting the server fixes this, but RAM usage doesn't decrease until I shutdown and restart WSL. Strangely, only Windows appears to be aware of this memory usage - If I check usage in WSL using htop everything looks normal.

**Comment by oobabooga** [comment]
This looks like a bug in exllama not the webui. The memory is not released when the relevant objects are destroyed by `unload_model()`. I'll be annoying and tag @turboderp

**Comment by turboderp** [comment]
It's not a bug, it's an unfinished feature. :)

But no, the model is mostly stored in PyTorch tensors that are released when the instance is dereferenced and garbage collection happens. There are a few relatively small device buffers and native/unmanaged objects that will stick around, though. I just haven't decided on an approach to cleaning them up yet, as it gets a little tricky when the model's destructor is called automatically after the CUDA context is destroyed.

I guess I can add a function to explicitly unload all the unmanaged parts of the model. If you want to be able to load multiple instances concurrently I'll have to do a little extra work on that as well.

**Comment by matatonic** [comment]
My use case is just being able to change models without restarting the server. I load some with autogptq, some with exllama and some with llama.cpp (maybe more), run some tests and then load the next model - So for me anyways, concurrent no, but sequential yes.

**Comment by abrisene** [comment]
> It's not a bug, it's an unfinished feature. :)

@turboderp - Thank you for your work in any case. The increase in performance, VRAM efficiency and ease of loading that you've enabled with exllama significantly outweighs the pain in the ass of having to restart the webui each time I want to load a new model.

The RAM issue I observed is probably unrelated to exllama, since I updated llama.cpp to support GPU offloading at the same time, but I've observed it with both GGML & GPTQ models.

**Comment by Ph0rk0z** [comment]
It's interesting that the 2nd model you load is destroyed completely. It's only the 1st one that gets stuck.

Moving the generator to result from self lets it free most of the memory. 500mb out of ~5 or so gigs remains of the 7b vs the entire thing.

I haven't checked yet what happens for a 30b or 65b when you go to switch models. Either way, some of your vram is gone until you restart textgen. Not great, not terrible.

**Comment by oobabooga** [comment]
@Ph0rk0z can you submit that as a PR? That's a bug fix.

**Comment by turboderp** [comment]
It's worth noting that PyTorch allocates a bunch of memory of its own that won't be freed until you end the process. This isn't part of the model, but it does use lazy initialization so the VRAM usage only shows up when the model is loaded. It shouldn't matter, though, since it wouldn't allocate more when the second model is loaded.

**Comment by matatonic** [comment]
Confirmed the latest update is working, thanks all!

**Comment by turboderp** [comment]
For completeness I added a `free_unmanaged()` function which you should call before unloading the model. There aren't currently any unmanaged CUDA buffers to free, but that could change in the future. Currently there are some tiny `Q4Matrix` objects making up a few kB of system RAM in total for a model. So those would leak. Perhaps more importantly there are CUDA stream and event handles allocated per device, and I'm not sure how many of those you have to leak before it becomes an issue for the CUDA runtime. 

`free_unmanaged()` should clear it all out in any case, and afterwards, once the model falls completely out of scope, you can call `torch.cuda.empty_cache()` to get most of your VRAM back. I say most because Torch still allocates some for its internal buffers, and apparently the CUDA runtime has a bit of VRAM overhead, too. Both use lazy initialization so the overhead only materializes once a model is loaded and used for the first time. But it remains constant after that, no matter how many models are loaded and unloaded.

I checked and there seems to be no way to completely destroy/restart a Torch instance without destroying the whole process, but there also wouldn't be any benefit to it unless you actually need that last GB or so for something other than PyTorch model. `torch.cuda.empty_cache()` is usually unnecessary for the same reason.
