### ISSUE TITLE
Add tabs to make the interface more like AUTOMATIC1111

### ISSUE THREAD

**Issue by oobabooga** [oobabooga/text-generation-webui#293]
As new features and functionalities become available, additional GUI elements will need to be added, and the current layout is already cramped.

The interface needs to have some kind of tabbed layout with a navigation header.

**Comment by MetaIX** [comment]
I agree. Perhaps instead of specifying --cai-chat, etc. to change the UI layout at startup, we could have different tabs that switch between different "modes." For example a tab for cai chat, a tab for the default inference ui, etc. It'd make it easier in the long run to add new "modes" like, for instance, a Novel-AI mode to develop stories. Also, would it be possible to make it so that the models are loaded within the UI?

**Comment by oobabooga** [comment]
Yes, loading models in different modes from within the web UI (8bit, etc) is a long term goal. Having all modes coexist would be cool too. 

But I think that the most pressing issue for now is adding an "Extensions" tab where extensions can be activated or deactivated on the fly without the need for command-line flags, just like AUTOMATIC1111 does.

Gradio has `gr.Tab()`, but I feel like adding the chat box into a tabbed layout breaks immersion and makes the interface look weird. It's an open problem for me how to add tabs in a cleaner way.

**Comment by Enferlain** [comment]
Feel like the previous was better. Also colab gradio now disconnects after whatever changed between today and yesterday, but hopefully just a single random occurrence

**Comment by oobabooga** [comment]
* A header menu is now available
* Settings are better compartmentalized by category using tabs
* An option to switch between different modes and activate/deactivate extensions on the fly has been added

I consider that the goals have been reached, so I am closing the issue.

**Comment by MetaIX** [comment]
Wow, these changes are great and bring so much convenience. Insane. Thank you!
