### ISSUE TITLE
Multimodal Support for Llava-Llama-2-4bit?

### ISSUE THREAD

**Issue by chigkim** [oobabooga/text-generation-webui#3293]
**Description**

There's new Llava model based on Llama-2.
https://huggingface.co/liuhaotian/llava-llama-2-13b-chat-lightning-preview
Could you implement so that Multimodal could support the model?

**Additional Context**
I've quantized the above model to 4-bit using .

```
git clone https://github.com/oobabooga/GPTQ-for-LLaMa.git -b cuda
cd GPTQ-for-LLaMa
pip install -r requirements.txt
python setup_cuda.py install
python llama.py ../models/liuhaotian_llava-llama-2-13b-chat-lightning-preview c4 --wbits 4 --true-sequential --groupsize 128 --save_safetensors ../models/liuhaotian_llava-llama-2-13b-chat-lightning-preview/liuhaotian_llava-llama-2-13b-chat-lightning-4bit-128g.safetensors
```

Then I loaded with --multimodal-pipeline llava-13b.

`python server.py --verbose --share --chat --model-dir ../models --model liuhaotian_llava-llama-2-13b-chat-lightning-preview --loader exllama --max_seq_len 4096 --xformers --no-stream --deepspeed --multimodal-pipeline llava-13b`

I tried many different images, but the descriptions are completely incorrect. I.E. I submitted a picture a dog, and it said woman holding an umbrella.

Since the model loads and outputs proper English, I assume it's quantized correctly.

**Comment by Ph0rk0z** [comment]
There is also https://github.com/luogen1996/LaVIN but I've yet to see if it works.

**Comment by yusin2it** [comment]
also to me, if someone know, please !

**Comment by Fusseldieb** [comment]
Same issue!

**Comment by haotian-liu** [comment]
Hi, I am the author of LLaVA and I am working on the integration of LLaVA. An initial PR is submitted here: https://github.com/oobabooga/text-generation-webui/pull/3377

Please try it out :)

And also the full story here: https://github.com/haotian-liu/LLaVA/issues/310#issuecomment-1657552223

If you are familiar with LLM quantization, please kindly help with some of the issues that I am having currently.

Thanks.

**Comment by chigkim** [comment]
Confirmed it works!!!
Closing the issue.

**Comment by yusin2it** [comment]
Since the problem is sloved but I still have a bit problem with  the checkpoint liuhaotian_llava-llama-2-13b-chat-lightning-preview.

May I ask here why I always have this "KeyError: 'llava'".


root@8e827d585b09:/workspace/text-generation-webui# python server.py --model liuhaotian_llava-llama-2-13b-chat-lightning-preview --multimodal-pipeline llava-llama-2-13b --api --extensions multimodal
bin /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
2023-08-01 06:56:35 INFO:Loading liuhaotian_llava-llama-2-13b-chat-lightning-preview...
Traceback (most recent call last):
File "/workspace/text-generation-webui/server.py", line 1151, in
shared.model, shared.tokenizer = load_model(shared.model_name)
File "/workspace/text-generation-webui/modules/models.py", line 79, in load_model
output = load_func_map[loader](https://github.com/oobabooga/text-generation-webui/pull/model_name)
File "/workspace/text-generation-webui/modules/models.py", line 140, in huggingface_loader
config = AutoConfig.from_pretrained(path_to_model, trust_remote_code=shared.args.trust_remote_code)
File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 998, in from_pretrained
config_class = CONFIG_MAPPING[config_dict["model_type"]]
File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 710, in getitem
raise KeyError(key)
KeyError: 'llava'
