### ISSUE TITLE
Missing words when generating with llama.cpp backend and GGUF model.

### ISSUE THREAD

**Issue by JohanAR** [oobabooga/text-generation-webui#3708]
### Describe the bug

When using the latest version after gguf merge (commit 0c9e818bb874df6429bf1c5fe96be6400516abd9), generated text appears to be missing some words.

Example:
> Common sense questions and answers
>
> Question: Why is the sky blue?
> Factual answer: The sunlight bounces off molecules in our, which scatter light. Blue light gets more than other colors, causing the sky to look blue.

The word "atmosphere" is clearly missing in the answer. I also noticed that it seems to be consistent which words are missing, if I ask other questions. If I use the word in the question, the answer becomes nonsensical.

> Common sense questions and answers
>
> Question: What is the atmosphere?
> Factual answer: "The cat." 

I started [a discussion](https://github.com/ggerganov/llama.cpp/discussions/2822) about it on llama.cpp's repo yesterday since I wasn't sure what was causing the issue, and at least one other person confirmed that they had the same issue when using text-generation-webui gguf2 branch. The issue seems to be absent when running llama.cpp's example program using the same model.

The model I used in this example was airoboros-33b-gpt4-2.0.ggmlv3.q5_K_M.bin (TheBloke) converted to GGUF using llama.cpp converter scripts. The issue has been reproduced on multiple GGUF models.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Probably reproducible when using any GGUF model with llama.cpp backend in text-generation-webui.

### Screenshot

See examples as text above.

### Logs

Github refused to let me paste the log here, however there are no errors or anything out of the ordinary in it.
```shell
text-generation-webui-text-generation-webui-1  | llama_model_loader: - type  f32:  121 tensors
text-generation-webui-text-generation-webui-1  | llama_model_loader: - type q5_K:  361 tensors
text-generation-webui-text-generation-webui-1  | llama_model_loader: - type q6_K:   61 tensors
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: format         = GGUF V1 (latest)
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: arch           = llama
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: vocab type     = SPM
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: n_vocab        = 32000
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: n_merges       = 0
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: n_ctx_train    = 2048
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: n_ctx          = 2048
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: n_embd         = 6656
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: n_head         = 52
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: n_head_kv      = 52
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: n_layer        = 60
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: n_rot          = 128
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: n_gqa          = 1
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: f_norm_eps     = 1.0e-05
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: f_norm_rms_eps = 1.0e-06
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: n_ff           = 17920
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: freq_base      = 10000.0
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: freq_scale     = 1
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: model type     = 30B
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: model ftype    = mostly Q5_K - Medium (guessed)
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: model size     = 32.53 B
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: general.name   = airoboros-33b-gpt4-2.0.ggmlv3.q5_K_M.bin
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: BOS token = 1 '<s>'
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: EOS token = 2 '</s>'
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: UNK token = 0 '<unk>'
text-generation-webui-text-generation-webui-1  | llm_load_print_meta: LF token  = 13 '<0x0A>'
text-generation-webui-text-generation-webui-1  | llm_load_tensors: ggml ctx size =    0.17 MB
text-generation-webui-text-generation-webui-1  | llm_load_tensors: using CUDA for GPU acceleration
text-generation-webui-text-generation-webui-1  | llm_load_tensors: mem required  = 13268.48 MB (+ 3120.00 MB per state)
text-generation-webui-text-generation-webui-1  | llm_load_tensors: offloading 24 repeating layers to GPU
text-generation-webui-text-generation-webui-1  | llm_load_tensors: offloaded 24/63 layers to GPU
text-generation-webui-text-generation-webui-1  | llm_load_tensors: VRAM used: 8711 MB
```

### System Info

```shell
Fedora Linux 38 (KDE Plasma)
Linux hostname 6.4.11-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Aug 16 17:42:12 UTC 2023 x86_64 GNU/Linux
RTX3080 12GB
```

**Comment by JohanAR** [comment]
Found some comments on discord indicating that this issue might be present in other projects that use llama-cpp-python, so hopefully it's fixed in version 0.1.80 which was recently released.

**Comment by JohanAR** [comment]
Likely caused by this bug in llama-cpp-python: https://github.com/abetlen/llama-cpp-python/issues/642

**Comment by FartyPants** [comment]
Hello
Greetings, I am here to provide. Is there you need help with?

**Comment by JohanAR** [comment]
I think the bug is being addressed in llama-cpp-python, someone has submitted a PR there but it hasn't been accepted yet. Then https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels will need to be rebuilt for the new version, and after that text-generation-webui can update the requirement. So I think all we can do now is to wait :)

**Comment by Undi95** [comment]
The issue is fixed in the last commit from 15 minutes ago. We just need to wait for the wheels like JohanAR said

**Comment by evil-brain** [comment]
I can confirm that v0.1.81 fixes the issues

I manually installed llama-cpp-python v0.1.81 (CPU-only) into my Conda env and tested with codellama-34b-instruct.Q5_K_M.gguf; no issues with  missing words or munged output anymore!

**Comment by JohanAR** [comment]
Resolved by #3716

**Comment by Susanoo1337** [comment]
I don't know if it's not actually been resolved, or became unresolved recently. As of yesterdays comitt [0576691](https://github.com/oobabooga/text-generation-webui/commit/0576691538da4f93d50b9ee28c252eb91c4f0da3) this issue seems to still persist. I can reproduce it with any 13B GGUF model. Once the conversation has dragged on for a while, words like "to, the, of" etc., as well as some pronouns and commata as well as periods stop generating. I don't have a 7B GGUF to try, but a 7B GGML loaded in llama.cpp produces similar results, albeit less consistent.
GPTQ loaded using ExLlama_HF had no such problems, I couldn't test it using AutoGPTQ since I only have 12GB VRAM.

**Comment by JohanAR** [comment]
I haven't noticed any issues after the fix was merged. Primarily been using Mythomax-l2-13b GGUF q5_k_m, and up to the model's max context.

What model(s) were you using? What's your n_ctx set to, and how many tokens are you sending to the model when the problem begins to appear? If you're using the chat tab you can press the "send to notebook" button as soon as it happens, but I think you need to do something like adding a letter at the end and removing it for it to update the token counter.

**Comment by Susanoo1337** [comment]
Ok I spent some time bringing it to a breaking point today, I figured out too late the "Send to notebook" only sends the truncated context to notebook so my numbers are a little bit off, but the final breaking point I measured using the entire chatlog and a different tokenizer.

n_ctx and truncation is set to 4096.
First failure was at 1956 tokens, but regenerating the response fixed it 1/3 of the time.
Second Failure was at 3141 tokens, however regenerating the response still fixed it.
The third and final failure occured at 3451 context tokens, with the entire conversation being 5311 tokens long.
Regenerating the response always resulted in text with plenty of "to, the, by, of" as well as punctuation missing.

The model used was athena-v1.Q5_K_M.gguf: https://huggingface.co/TheBloke/Athena-v1-GGUF

Switching to athena-v1.Q4_K_S.gguf produced the same broken output.
(I've had previously also tested this using other models like airoboros and nous-hermes-llama2 with the same results)

Switching to the ctransformers model loader, using athena-v1.Q5_K_M.gguf and regenerating the response produces error-free output. Which leads me to suspect that the issue is unique to llama.cpp
I've had conversations in excess of 10k tokens (always 4096 n_ctx) in which the problem didn't occur even once using ctransformers.

My GPU is a 3060 12GB
CPU is a i9-9900k with 32GB ram

n-gpu-layers = 35
n_ctx = 4096
threads = 2
n_batch = 512

I haven't thoroughly tested it, but last time I tried setting n_batch = 256, the problem started occurring quite a bit later into the conversation. Might be coincidental.
