### ISSUE TITLE
GGUF preforms far worse than GGLM

### ISSUE THREAD

**Issue by Delcos** [oobabooga/text-generation-webui#3714]
### Describe the bug

I've tested using 2 models, the stock Llama 2 70b chat and Deepnight 70b. Both 8 bit, and both working, but the GGUF preforms much worse consistently even over the same seeds. It will leave sentences unfinished but still add a '.' at the end, has poor problem solving, etc. I made sure all settings were correct for GGUF and everything is up to date.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

It's reproducible just by loading the models and comparing result.

### Logs

```shell
N/A
```

### System Info

```shell
128gb RAM
24 gb VRAM Nvidia
Linux (Known good)
```

**Comment by Undi95** [comment]
There's a problem with the build of llama.cpp-python used in the webui atm.
I think this issue is related : https://github.com/oobabooga/text-generation-webui/issues/3708
It was fixed in the last build : [v0.1.81](https://github.com/abetlen/llama-cpp-python/releases/tag/v0.1.81)

We need to wait for an update of the webui who use this build, then GGUF file will be usable.
