### ISSUE TITLE
Can't load model elyza_ELYZA-japanese-Llama-2-7b-fast

### ISSUE THREAD

**Issue by almagest21** [oobabooga/text-generation-webui#3741]
### Describe the bug

Hi, I tried this model but I can't load the model.
https://huggingface.co/elyza/ELYZA-japanese-Llama-2-7b-fast

Could you check this issue?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Download elyza_ELYZA-japanese-Llama-2-7b-fast model firstly.
Then load the model.

### Logs

```shell
2023-08-29 15:46:03 INFO:Loading elyza_ELYZA-japanese-Llama-2-7b-fast...
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.79s/it]
2023-08-29 15:46:11 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "D:\llama\webui\text-generation-webui\modules\ui_model_menu.py", line 190, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "D:\llama\webui\text-generation-webui\modules\models.py", line 87, in load_model
    tokenizer = load_tokenizer(model_name, model)
  File "D:\llama\webui\text-generation-webui\modules\models.py", line 104, in load_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
  File "D:\llama\webui\installer_files\env\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 727, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "D:\llama\webui\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(
  File "D:\llama\webui\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py", line 2017, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "D:\llama\webui\installer_files\env\lib\site-packages\transformers\models\llama\tokenization_llama.py", line 156, in __init__
    self.sp_model = self.get_spm_processor()
  File "D:\llama\webui\installer_files\env\lib\site-packages\transformers\models\llama\tokenization_llama.py", line 162, in get_spm_processor
    with open(self.vocab_file, "rb") as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### System Info

```shell
Windows 11
NVidia Geforce 3090
Latest text-generation-webui version
```

**Comment by kik0220** [comment]
This problem seems to be caused by the lack of tokenizer.model in elyza/ELYZA-japanese-Llama-2-7b-fast and elyza/ELYZA-japanese-Llama-2-7b-fast-instruct.
I was able to load both by copying [tokenizer.model](https://huggingface.co/elyza/ELYZA-japanese-Llama-2-7b-instruct/blob/main/tokenizer.model) from elyza/ELYZA-japanese-Llama-2-7b-instruct.

**Comment by kik0220** [comment]
It can be loaded, but it seemed to be in a problematic state.
sorry.
https://huggingface.co/elyza/ELYZA-japanese-Llama-2-7b-fast-instruct/discussions/1

**Comment by almagest21** [comment]
@kik0220 Thank you for your information. Do you know is it mandatory file for webui?
The model's sample script seems to be able to run without tokenizer.model.

**Comment by kik0220** [comment]
@almagest21 Sorry i don't know.

**Comment by kik0220** [comment]
@almagest21 I carefully read [Missing tokenizer.model](https://huggingface.co/elyza/ELYZA-japanese-Llama-2-7b-fast-instruct/discussions/1#64edba3f453a4b4bef378257) and found out that tokenizer.model is derived from sentencepiece.
And elyza/ELYZA-japanese-Llama-2-7b-fast and elyza/ELYZA-japanese-Llama-2-7b-fast-instruct are loaded with Fast (use_fast=True) instead of from sentencepiece and tokenizer.model doesn't use .
So, if the model name had fast attached, I loaded the tokenizer with [use_fast=True](https://github.com/oobabooga/text-generation-webui/compare/main...kik0220:text-generation-webui:load_use-fast), and it was loaded successfully and I was able to generate text.
Since it's a crude method, I won't make a pull request.

**Comment by almagest21** [comment]
@kik0220 Thank you very much for your code. I confirmed that the model is successfully loaded using your changes.
@oobabooga Could you consider to add UI for "use_fast=True" setting. I believe it is needed to be set by user. Ideally it is good to be set automatically without user's judge (someway to decide to set from model's any information, or using model name Database, etc.).

**Comment by kik0220** [comment]
@almagest21 If it's a new feature proposal, can the label remain a bug? Can it be changed?

**Comment by almagest21** [comment]
@kik0220 Adding UI is new feature actually as you mentioned but I believe current behavior (can't load this model) is bug or unexpected action. Also I do not seem to have permission to change label.
