### ISSUE TITLE
I would like to see the old chat UI returned

### ISSUE THREAD

**Issue by Artabanos** [oobabooga/text-generation-webui#3907]
Hello,
 I have been using text-generation-ui for a few months now and am happy about every further development that has been incorporated into the project. Thank you for that.

However, I would like to express a wish. After today's update I discovered that the controls I use most often are hidden behind a hamburger menu. In my opinion, the usability suffers. I would simply like to have the buttons under the input line back. Maybe as a selection option?

Ironically, the controls I never use are left within easy reach. (I've never used "Start relpy with", I only use chat mode and I never change the chat style.)

**Comment by mykeehu** [comment]
[Many of us are asking for the old interface back](https://github.com/oobabooga/text-generation-webui/commit/5e3d2f7d447700076fa66fb33f991d561da0a94b#comments), but I don't see any development in that direction yet :(

**Comment by YakuzaSuske** [comment]
I agree to have have an option for the old UI or atleast a fix for the new one. When i hit the "remove last reply" the tab just disappears.... like bruh! What if i had more stuff to remove? Just leave the tab open and let me click it over and over until i stop hovering my mouse over it.

**Comment by oderwat** [comment]
I was shocked after the update. This new menu really is a terrible idea. It takes much longer to click regenerate or remove the last reply. If the size was a problem, add some icons instead of the buttons. Or make the button fold up in that new menu style and save the state of that fold in the settings.

**Comment by RandomInternetPreson** [comment]
In Auto1111 they did something similar, but gave users an option to have the buttons displayed instead of in a menu.  I'd like to see something like that in this case.  Sometimes when I am diagnosing or testing things I need to press certain buttons a lot, but now that they are in the hamburger menu it adds an extra step and I have to make sure I read which button I'm clicking instead of just memorizing where it was.

**Comment by oobabooga** [comment]
I have added keyboard shortcuts that should add back the ease of use while maintaining the new UI. https://github.com/oobabooga/text-generation-webui/commit/fc11d1eff0e311f2551bac083846407d45b8a670

**Comment by FartyPants** [comment]
Can someone post a screenshot? If I should update or not...

**Comment by missionfloyd** [comment]
@FartyPants You can revert to the way it was before with `git reset --hard 34dc7306b8cb8976ea55b692bbe4260629dd8f56`

**Comment by oderwat** [comment]
> I have added keyboard shortcuts that should add back the ease of use while maintaining the new UI. [fc11d1e](https://github.com/oobabooga/text-generation-webui/commit/fc11d1eff0e311f2551bac083846407d45b8a670)

This is not the same as having the buttons, and adds more cognitive burden on the user. What is the problem with making the buttons optional (and probably using icons to make them take less room)? I think that this "new UI" is unfortunate. I hate being restricted because somebody wants to use the tool on a mobile screen, while I have three huge monitors.

**Comment by RandomInternetPreson** [comment]
Interesting idea with the shortcut buttons, I think that would work as an alternative to the menu.

**Comment by mykeehu** [comment]
😢 Then maybe a programmer should write an extension for it 🙄

**Comment by BadisG** [comment]
@oobabooga Why won't you just put the old buttons back? How hard is that? Just add an option to get this possibility so that everyone is happy?
