### ISSUE TITLE
Add AVX512 builds to requirements

### ISSUE THREAD

**Issue by sammcj** [oobabooga/text-generation-webui#3994]
**Description**

It might be nice to have AVX512 support added for modern CPUs to take advantage of.

**Additional Context**

At present I have a fork of this repo that I add the AVX512 packages to such as those kindly built by @jllllll https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/AVX512/ / https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/AVX512/

I can submit a PR to add them into the requirements.txt - but I wanted to check if there's any reason why they're not already included and see if @jllllll had any input / concerns.

**Comment by jllllll** [comment]
They aren't included because they can't be simultaneously installed with the AVX2 wheels.
pip does not provide a way to differentiate CPUs. Adding those wheels to the requirements.txt will either just not work, or will result in one or the other being installed depending on the order they are listed.

It wouldn't be hard to add such functionality to the one-click-installer, but that would leave out everyone not using it.

You might want to test how much of a difference AVX512 makes in llama.cpp. From what I've gathered in researching this, AVX512 is only really better than AVX2 in a handful of tasks. It is the same for most tasks and even worse in some others.

Another consideration is that Intel's support for AVX512 is shockingly minimal. Pretty much only the latest of their CPUs really supports it. Most of the older ones that support it only support a small subset of operations with it. They even gave up supporting it in the Alder Lake CPUs.

**Comment by sammcj** [comment]
Ahh understood, thank you so much for taking the time to write such a detail response - that's really interesting! I really appreciate it.
