### ISSUE TITLE
Solution to "CUDA Setup failed despite GPU being available."

### ISSUE THREAD

**Issue by oobabooga** [oobabooga/text-generation-webui#4260]
On some systems, Pytorch seems to not be installing necessary CUDA libraries even when you use the [correct command](https://pytorch.org/get-started/locally/).

I have managed to solve it with the following command:

```
conda install -y -c "nvidia/label/cuda-11.8.0" cuda-runtime
```

By running it after installing Pytorch, the following error should be solved:

```
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

```

Some more keywords to help people find this:

```
The following directories listed in your path were found to be non-existent
did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
```

**Comment by nickwood2009** [comment]
I ran this command, ubuntu 22.04 but still get the same error:
CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

**Comment by rkowalsk** [comment]
Install through the one-click-installer fails with this error. How do I fix this issue when using the one-click-installer on linux ?

**Comment by Galaxia-mk** [comment]
Thank you so much! I had infinite trouble since Nvidia changed driver 515 to 525 and was forced to use cuda 12. I tried many things but because I'm not super familiar with linux I messed up the drivers and the cuda and eventually decided to reinstall the pc. 

I didn't use the one click installer (because that has never worked or worked properly for me). I installed the web UI manually and like Ooba said ran that command right after installing pytorch.

Though please look into improving the "pip install -r requirements.txt --upgrade". It has never worked properly for me. I had to reinstall the WebUI for AWQ and Exllamav2 support for example. I had to reinstall the webUI again but this time I couldn't reinstall it because of cuda incompatibility. I run a distro based on ubuntu 22.04

**Comment by randoentity** [comment]
The solution for me was either a reboot or:
```sh
sudo rmmod nvidia_uvm
sudo modprobe nvidia-uvm
```
