### ISSUE TITLE
Legacy API CLI Arguement

### ISSUE THREAD

**Issue by saphtea** [oobabooga/text-generation-webui#4581]
**Description**

I'd like to have an implementation of the legacy API as a cli arguement. Since we're converting to an openai formatted API it has broken any and all discord bot programs I was using before and a lot of the devs are either inactive or don't want to update it due to frequent API changes in ooba. If this is at all a possibility I think it would help keep the ecosystem alive. I don't want to stay on older versions of Ooba for the sake of getting fixes for multimodal pipelines and the likes.

**Comment by ashleykleynhans** [comment]
Agreed, its fine to deprecate things, but not fine to give people only a few days before completely removing the deprecated functionality.  Please add back the deprecated/legacy APIs so that users have sufficient time to migrate across to the new Open AI compatible API.   By the way, why is is it "OPENEDAI" in the docs instead of "OPENAI" ?

**Comment by neker97** [comment]
I would to know that if there's a possibility to use old API's i don't want to use OPENAI API's, i have read the doc at http://127.0.0.1:5000/docs but it's not so useful

**Comment by WouterGlorieux** [comment]
I agree, there should be an option to use the legacy API, I didn't even know it would be deprecated until my app stopped working today. So far I'm unable to get the new openai extension working with 'TheBloke Local LLMs One-Click UI and API' on runpod.

Does anyone have some simple python example to get this working?

**Comment by ashleykleynhans** [comment]
@WouterGlorieux You can use [my template](https://runpod.io/gsc?template=el5m58e1to&ref=2xxro4sy) on RunPod in the mean time, it still has the legacy REST API on port 6000, the legacy WebSockets API on port 6005 and the new Open AI compatible API on port 5000.

This is only because it uses an older commit though.  Ideally we should still be able to use the legacy/deprecated API for a few months and given a chance to migrate to the Open API compatible API over time though.

**Comment by WouterGlorieux** [comment]
@ashleykleynhans I can't seem to get your template working, none of the 'connect' buttons opens up the webui, all lead to a page saying the port isn't open yet.

**Comment by ashleykleynhans** [comment]
@WouterGlorieux you need to wait for everything to sync to /workspace, view the container logs to view the progress.

**Comment by oobabooga** [comment]
Both APIs are self-contained extensions. You can download [this snapshot](https://github.com/oobabooga/text-generation-webui/archive/refs/tags/snapshot-2023-11-12.zip), move the `extensions/api` folder in the zip to `text-generation-webui/extensions/api`, and start the old API with `--extensions api`. The old API can be used indefinitely like this.

I recommend migrating to the new API as it has a documentation, proper types for input parameters, more reliable streaming (SSE instead of websockets), and a better syntax for the chat endpoints. Since it follows a widely adopted schema, your scripts will be more future-proof and will work with minor or no changes with other projects, for instance, [vLLM](https://github.com/vllm-project/vllm).

https://github.com/oobabooga/text-generation-webui/wiki/12-%E2%80%90-OpenAI-API

**Comment by ashleykleynhans** [comment]
Thanks for the awesome work on this project.  I agree that ultimately migrating to the Open AI API is the way forward, just needed a stop gap while the migration is taking place.  Thanks for the link to the snapshot, I've put it into a GitHub repo so the legacy API can be installed easily from there for people who need to migrate their applications to the new API.

**Comment by helix4u** [comment]
if you do the whole workaround to grab the API extension to use with things until they're fixed, ya might have to add the following back to shared.py as the API depends on them being present:

parser.add_argument('--api-blocking-port', type=int, default=5000, help='DEPRECATED')
parser.add_argument('--api-streaming-port', type=int, default=5005, help='DEPRECATED')

**Comment by helix4u** [comment]
![image](https://github.com/oobabooga/text-generation-webui/assets/4317663/227eda0e-0851-419b-b910-00d4ed9d6c2d)
You'll also need to add back in the blocking port and junk into shared.py because the old API extension depends on these.
