### ISSUE TITLE
sd_api_picutres temporarily flashing images when forcing pictures (solution provided)

### ISSUE THREAD

**Issue by RandomInternetPreson** [oobabooga/text-generation-webui#465]
### Describe the bug

When doing anything other than prompting the AI to send a picture, like forcing a picture on the next request, the image only shows briefly in the chat box area.

This can be fixed by adding "shared.args.no_stream = True" to line 150 in the script.py file.  This is where def force_pic() is declared.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just try forcing a picture, you can save the picture to the hard disk, but you can't keep it in the chat window.

### Screenshot

![issue](https://user-images.githubusercontent.com/6488699/226510387-aeabc1a8-d31a-404e-8602-7686c61cb498.png)

### Logs

```shell
NA
```

### System Info

```shell
Windows 10, 4090, i9 13900k
```

**Comment by Brawlence** [comment]
Fixed in #596 

([the line in question](https://github.com/oobabooga/text-generation-webui/pull/596/files#diff-3918965e2a344d3e5543871949fc3c01353cf9e542d0d913c96f697a66de871aR215))

This issue can be closed.

---

Also @oobabooga while you're at it, can you also close #533? The same PR handled that too.

**Comment by oobabooga** [comment]
Thank you @Brawlence
