### ISSUE TITLE
Generation slows at max context, even when truncated

### ISSUE THREAD

**Issue by TheInvisibleMage** [oobabooga/text-generation-webui#5337]
### Issue Summary
When generating, if the context is near the maximum set via n_ctx (and the truncate value in Parameters is set to match it), generation will be quite slow. This does not occur if the context is more than approximately 300-500 below the set value. It still occurs even if the n_ctx and truncation numbers are reduced (though the slowdown becomes less severe.

### Observations

- Since speed is perfectly fine up until we near the context limit, then immediately drops, I suspect this has something to do with how the context is truncated; the actual act of truncating the input seems to cause the slowdown, despite the fact that this should be a simple operation.
- Increasing the limit back up after lowering also does not help;; makes sense, since it just pulls in as much of the conversation as will fit and hits the context limit again, requiring truncation. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- Set your n_ctx to a given value. (In my case, 8192).
- Chat with the model, noting the speed. At this point, it should be fairly rapid. (In my case, 4.72 tokens/s up to context 7792).
- As soon as the context reaches approximately 7800, generation slows. (In my case, 0.87 tokens/s on the message immediately after the above, at context 7798).
- At this point, reducing n_ctx and reloading the model only partially helps. (In my case; reducing to 4092 produced 2.51 tokens/s at context 3641.

### Logs

```shell
N/A
```

### System Info

```shell
- Model: TheBloke/Silicon-Maid-7B-GGUF, using the 5_K_M quant.
- Branch: dev
- Commit: 8962bb173e9bdc36eb9cf28fe9e1952b2976e781
- OS: Windows 11
```

**Comment by TheInvisibleMage** [comment]
I may have a theory for this one: rather than relating to the truncation directly, it may be due to prefix-matching in llama.ccp.
Essentially:

- The "fast" speeds above are when the prefix-match occurs. I'm not familiar with the internals of llama.ccp, but I believe this just indicates a cache was hit, allowing the model to effectively "skip processing" for a chunk of the prompt.
- When the maximum context is reached, the "left-most" part of the context is cut off, meaning that the prompt appears to start differently.
- The theory goes that this "new" prompt cannot match the cached values because it starts differently, even if almost all the info within it matches previous runs. However, I'm still getting the "Llama.generate: prefix-match hit" message, so I'm unsure of whether this is a valid theory.

**Comment by TheInvisibleMage** [comment]
Given the above, I don't think this is a bug so much as a limitation of the cache; if the cached information was chunked smaller (per chat message?), multiple checks against the cache could lead to significant speed improvement, but that's more of an enhancement, and probably more something for the llama.cpp repo than this one.

**Comment by poipoi300** [comment]
I'd suggest enabling streaming_llm in the model config tab. 

I will comment as to why this is happening for anyone curious and to answer @TheInvisibleMage's theory.
You're correct that it occurs from a cache mismatch. However, the problem is deeper than that and splitting the cache into smaller chunks would not solve the issue.

What's being cached is the probability of each token being there given the previous tokens. If you have 3 parts, keep part 1, 3 and add 4, suddenly the probability associated with 3 doesn't follow 1. You need to re-calculate that. It's not the same probabilities anymore. Since the probability of 3 following 1 has been updated, we also need to update 4, 5, 6 etc. From my understanding, the option I've mentioned fixes that by accumulating probabilities into sink tokens, though I ain't no statistician and I didn't look into it.
