### ISSUE TITLE
All characters replying with 'Char:' in this version

### ISSUE THREAD

**Issue by spike4379** [oobabooga/text-generation-webui#6237]
### Describe the bug

I loaded a fresh install yesterday using the current version and now every character replies with their name. So if my character is named amy there will always be segments where it starts with 'Amy:' 
Has anyone else came across this? Characters are all used using the oobabooga template they provided online.

Edit: all models are using EXLlamav2. Reverting back to the prior version of oobabooga has stopped the models from working incorrectly.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

As I have no seen this reported I am more asking if others have encounted it and have found a solution. The simple method is to run a character card and see if they begin to reply in the same way.

### Logs

```shell
none
```

### System Info

```shell
5800x 4090, win 10
```

**Comment by gloic** [comment]
i had the same issue, i just found how to fix it.
It's related to the "Mode", the commit aa7c14a set 'chat-instruct' instead of 'chat'.
In Chat tab, i had no mode checked and the model used "char: " and "user: " very often. Once I selected a mode, this issue stopped.

To keep this value set, force an update of settings.yaml (Session > "Save UI defaults to settings.yaml"), it will add "mode: chat" or "mode: chat-instruct".

**Comment by spike4379** [comment]
Thank you gloic!
