### ISSUE TITLE
Add a flag for using all CPU threads in CPU mode

### ISSUE THREAD

**Issue by BugReporterZ** [oobabooga/text-generation-webui#8]
Depending on CPU architecture, memory bandwidth and workload, it might sometimes be beneficial to use all CPU threads in CPU mode instead of just physical threads. This can be accomplished by adding `torch.set_num_threads(t)` somewhere appropriate in `server.py`, with `t` being the number of desired threads. The image below shows what I did on my local installation to take advantage of all CPU threads with my i7-12700K.

Ideally this could be automatically set as the reported total CPU thread count, perhaps with a command line enabling flag so that the current default behavior remains for those cases where using all CPU threads is not helpful.

https://pytorch.org/docs/stable/generated/torch.set_num_threads.html

![image](https://user-images.githubusercontent.com/26941368/212686618-62f2ed88-3bda-45a1-a67c-d7a31e01f72d.png)

**Comment by oobabooga** [comment]
I have tried this in the past, and found that using all CPU threads caused a loss in performance compared to the default thread allocation done by pytorch.

Did you see a noticeable decrease in the time required to generate responses?

**Comment by BugReporterZ** [comment]
It's difficult to gauge exactly the gains without a deterministic benchmark, but admittedly they're not very large in my case. Still, I have the impression it consistently takes somewhat less time if I use all CPU threads rather than just physical threads. 

It seems to help mostly on longer computations (minutes-long) where CPU package power stays for longer periods at higher levels (150-190W), where presumably all CPU threads are working efficiently. Otherwise, for much of the time my CPU hovers around 100-110W with either 12 (physical only) or 20 (physical+logical) threads.

Note that I'm using Linux, so there could be differences from Windows.

**Comment by oobabooga** [comment]
I have evaluated the difference using these settings, which cause the inference to be deterministic:

```
do_sample=False,
max_new_tokens=tokens,
min_length=tokens,
```

These are the results on my i5-12400F in the current implementation vs using `torch.set_num_threads(12)`:

Mode | Prompt | Seconds
-- | -- | --
Current | This is my first input ever | 159.1035978794098
Current | In this story | 158.9810655117035
Current | Today we shall learn the | 158.97820615768433
All threads | This is my first input ever | 160.9279396533966
All threads | In this story | 160.8718876838684
All threads | Today we shall learn the | 160.78878092765808

I agree that this doesn't make sense, but pytorch doesn't get faster if you use all threads instead of just the physical threads.

**Comment by BugReporterZ** [comment]
I did a quick&rough test of 6 runs with 50 tokens using those settings and Pygmalion-6B Experimental for both all and just physical threads, using "Hi!" as a prompt; using all threads with my i7-12700K (12C/20T) and DDR4-3600 memory on Linux was not slower, but only barely faster. I'd need to time it better to be 100% sure, though.

Times in seconds. 

|T    | 1     |  2     |  3    | 4      | 5      |  6|
|---|---|---|---|---|---|---|
|20T| 17.3| 20.0| 20.0| 17.2| 17.2| 20.0|
|12T| 17.4 |20.3| 17.4| 20.4| 17.3| 20.3|
