### ISSUE TITLE
Downloading models from the web UI and exporting chat logs

### ISSUE THREAD

**Issue by neuralinternet** [oobabooga/text-generation-webui#9]
Hi Oobabooga, Thanks for the amazing work. Any chance you can add the ability for users on the UI to pick the model to then download/load to utilize? (https://github.com/abhishekkrthakur/diffuzers as an example which enabled users on the UI to select the model they wish to download/load) Also the ability for users on the UI to save chatlogs for any conversation just like ChatGPT?

**Comment by oobabooga** [comment]
What would the use case of exporting the chat logs be?

I have two problems with downloading models straight from the web UI:

1. Many of them are 10GB+ files that will take a while to download. 
2. Loading the model can be tricky. For low VRAM users, it involves trying different command-line flags until it works.

I will leave this issue open so that more people can add their thoughts.

**Comment by neuralinternet** [comment]
For the chatlogs it'll be useful because users will be able to go back to any saved conversation
